<a href="https://colab.research.google.com/github/raeesa1718/deeplearning/blob/main/rayeesa3142%20pnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

Scalar value: 5


# lab 1

In [ ]:
import numpy as np

# Scalar example
scalar = np.array(5)
print("Scalar value:", scalar)

# Vector example
vector = np.array([1, 2, 3])
print("Vector values:", vector)

# 2D Tensor (Matrix) example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (Matrix):\n", matrix)

# 3D Tensor example
tensor_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:\n", tensor_3d)

# 4D Tensor example
tensor_4d = np.random.rand(2, 3, 4, 5)
print("Shape of 4D Tensor:", tensor_4d.shape)


Scalar value: 5
Vector values: [1 2 3]
2D Tensor (Matrix):
 [[1 2 3]
 [4 5 6]]
3D Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 4D Tensor: (2, 3, 4, 5)


# **program to predict sum of two numbers**

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

# Step 1: Generate Training Data
def generate_data(num_samples):
    x1 = np.random.randint(0, 100, size=num_samples)
    x2 = np.random.randint(0, 100, size=num_samples)
    y = x1 + x2
    return np.vstack((x1, x2)).T, y

num_samples = 10000
X, y = generate_data(num_samples)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Define the Model
model = Sequential()
model.add(Dense(10, input_dim=2, activation='relu'))  # Input layer with 2 inputs
model.add(Dense(5, activation='relu'))  # Hidden layer
model.add(Dense(1))  # Output layer

# Step 3: Compile the Model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the Model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

# Step 5: Evaluate the Model
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

Epoch 1/50
200/200 [==============================] - 2s 4ms/step - loss: 2208.7046 - val_loss: 4.1262
Epoch 2/50
200/200 [==============================] - 0s 2ms/step - loss: 2.6005 - val_loss: 1.4545
Epoch 3/50
200/200 [==============================] - 0s 2ms/step - loss: 0.9544 - val_loss: 0.5821
Epoch 4/50
200/200 [==============================] - 0s 2ms/step - loss: 0.4400 - val_loss: 0.3298
Epoch 5/50
200/200 [==============================] - 0s 2ms/step - loss: 0.2888 - val_loss: 0.2446
Epoch 6/50
200/200 [==============================] - 0s 2ms/step - loss: 0.2227 - val_loss: 0.1917
Epoch 7/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1788 - val_loss: 0.1547
Epoch 8/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1473 - val_loss: 0.1282
Epoch 9/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1238 - val_loss: 0.1080
Epoch 10/50
200/200 [==============================] - 0s 2ms/step - loss: 0.1051 - val_loss: 0.0